# Generated by Django 3.2.5 on 2021-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Categories',
            field=models.CharField(choices=[('TC', 'Tecnologia'), ('CR', 'Curiosidades'), ('GR', 'Geral')], default='CR', max_length=2),
        ),
    ]
