# Generated by Django 3.2.5 on 2021-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Categories',
            field=models.CharField(choices=[('TC', 'Tecnologia'), ('CR', 'Curiosidades'), ('GR', 'Geral')], default='GR', max_length=2),
        ),
    ]
